# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Salary Prediction API

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.9", "3.10.10", "3.10.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up miniconda
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.10.11
        channels: conda-forge,defaults
        channel-priority: true
        activate-environment: lm_moel_to_cloud_env
        environment-file: starter/environment.yml
    - name: Install other dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 #pytest pandas scikit-learn fastapi httpx
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run server in background
      run: uvicorn main:app &
    - name: Test with pytest
      run: |
        pytest -vv
